### ISSUE TITLE
API vs Log Block Height

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/counterparty-core#2238]
I'm seeing this on my /v2 endpoint.
```
{
"result": {
"server_ready": false,
"network": "mainnet",
"version": "10.3.2",
"backend_height": 861808,
"counterparty_height": 859427,
"documentation": "https://counterpartycore.docs.apiary.io/",
}
}
```

But this in my journal:
```
[INFO] - Block 861808 - Parsing complete. L: 9b79a85, TX: 6f0c2f5, M: 1e20299 (0.05s)
[INFO] - Stopping prefetcher...
[INFO] - Catch up complete.
[INFO] - Watching for new blocks...
```

I've tried rolling back and `counterparty-server check-db`. Is a full reparse the solution?

Is there another command or operation I can try?

**Comment by ouziel-slama** [comment]
It seems to be a problem with the API database not being synchronized. Do you see any error message in the logs? Can you try restarting it with `-vvv`? also what branch are you using ?

**Comment by pinnate-modo** [comment]
Not sure if this is related but IIRC there's an issue where addrindexrs gets into a funny state any falls behind counterparty, which was fixed by restarting.

**Comment by ouziel-slama** [comment]
@droplister is the problem fixed ?

**Comment by pinnate-modo** [comment]
I knew this sounded familiar: https://github.com/CounterpartyXCP/counterparty-core/issues/1954

@droplister does [this](https://github.com/CounterpartyXCP/counterparty-core/issues/1954#issuecomment-2185875068) fix the issue?

**Comment by droplister** [comment]
I upgrade to 10.4 and it went away, but things i tried prior to that did not fix it.
