### ISSUE TITLE
Allow Comma-Separate `memo` and `memo_is_hex` for Sends and MPMA

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-core#2600]
Per https://github.com/CounterpartyXCP/counterparty-core/issues/2568,  in the v1 API it was possible to set `memo` (and `memo_is_hex`) to CSV. This was unspecified in the function signature (https://github.com/CounterpartyXCP/counterparty-core/blob/v9.61.3/counterpartylib/lib/messages/versions/mpma.py#L92) but it was documented for `send` at least (https://github.com/CounterpartyXCP/counterparty-core/blob/v9.61.3/counterpartylib/lib/messages/send.py#L108). We should add that functionality to the v2 API to approach parity with v1.

**Comment by ouziel-slama** [comment]
Done here https://github.com/CounterpartyXCP/counterparty-core/pull/2607

**Comment by jdogresorg** [comment]
FYI... the issue title is "Allow Comma-Separate `memo` and `memo_is_hex` for Sends in MPMA."

However, the implementation does not support comma-separate fields as it should :

`memo` became `memos` and requires a LIST :
`?memos=memo1&memos=memo2&memos=memo3` vs `memos=memo1,memo2,memo3`

`memo_is_hex` became `memos_are_hex` and accepts only a single value  :
`memos_are_hex=false` vs `memos_are_hex=false,false,true`

Glad the functionality was added back again, but still not able to pass a comma separated list as one would expect.

Perhaps consider making the specifying of multiple values comma-separated, as the other fields are, and/or give examples of how one should pass memos to the API, as it is not clear without an example

![image](https://github.com/user-attachments/assets/3102a65e-6df7-4e25-8cd3-2740bbe63e14)

**Comment by ouziel-slama** [comment]
> memo became memos and requires a LIST :

`memo` is still here and it's the default value if `memos` is not provided.

> but still not able to pass a comma separated list as one would expect.

yes to be backward compatible you should be able to use a comma in the memo.

>  as it is not clear without an example

will do but the doc seems to me clear: "one `memos` argument by send if any"

**Comment by jdogresorg** [comment]
Thank you for your response @ouziel-slama 👍 . I figured out how to get multiple memos to work in FreeWallet using the latest 10.6.1 release, however just wanted to clarify that still having issues with passing comma-separated lists for memo as your comment seems to indicate it should work.

### EXAMPLE 1 - Request with `memo` and comma separated list

https://api.counterparty.io:4000/v2/addresses/1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev/compose/mpma?destinations=1FwkKA9cqpNRFTpVaokdRjT9Xamvebrwcu%2Cbc1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2y5pdxx&assets=XCP%2CBACONTITS&quantities=123456780%2C1&memo=memo1%2Cmemo2&memo_is_hex=false&exact_fee=1000&allow_unconfirmed_inputs=true

FAIL - In this case, when passing a comma separated list of valies for `memo`, it is interpreted as a single memo

![image](https://github.com/user-attachments/assets/45dcd66c-b754-4201-bac4-8eb812fc2275)


### EXAMPLE 2 - Request with `memos` and multiple `memos` values

https://api.counterparty.io:4000/v2/addresses/1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev/compose/mpma?destinations=1FwkKA9cqpNRFTpVaokdRjT9Xamvebrwcu%2Cbc1q50kxp76j9l0k9jgwasvcz4mcz0v03fv2y5pdxx&assets=XCP%2CBACONTITS&quantities=123456780%2C1&memos=memo1&memos=memo2&memos_are_hex=false&exact_fee=1000&allow_unconfirmed_inputs=true

SUCCESS - This is the only way I have been able to get the current API to support multiple memos in an MPMA send... no way to specify a comma separated list of memos from what I can see.

![image](https://github.com/user-attachments/assets/e65acaa3-ebe8-459f-8dfd-07ef85fb4b79)

**Comment by ouziel-slama** [comment]
`memo` is still here but I didn't say it accepts a list ;-)

I just followed the mpma code (I don't wrote it) which accepts one default memo and one memo by send. So you can do something like this:

`...&memos=&memos=memo2&memos=&memo=toto`

the memo for send 1 and 3 will be `toto` and the memo of send 2 will be `memo2`

**Comment by jdogresorg** [comment]
lol.. seems pretty confusing logic.. but thank you for the example and explaining how `memo` and `memos` can be used in parallel to set a default memo or a per-send memo.

Much appreciated :) 👍
